stages:
  split:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw_data
    - src/data/make_dataset.py
    outs:
    - data/processed_data
  normalize:
    cmd: python src/data/minmax_scaling.py
    deps:
    - data/processed_data
    - src/data/minmax_scaling.py
    outs:
    - data/scaled_data
  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
    - data/processed_data/
    - data/scaled_data/
    - src/models/gridsearch.py
    outs:
    - models/best_params.pkl
  train:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data/y_train.csv
    - data/scaled_data/X_train_scaled.csv
    - src/models/train_model.py
    outs:
    - models/trained_model.joblib
  evaluation:
    cmd: python src/models/evaluate_model.py
    deps:
    - data/processed_data/
    - data/scaled_data/
    - models/trained_model.joblib
    - src/models/evaluate_model.py
    metrics:
    - metrics/metrics.json:
        cache: false
