stages:
  split:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw_data/raw.csv
    - src/data/make_dataset.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize:
    cmd: python src/data/minmax_scaling.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/minmax_scaling.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/gridsearch.py
    outs:
    - models/best_params.pkl
  train:
    cmd: python src/models/train_model.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/models/train_model.py
    outs:
    - models/trained_model.pkl
  evaluation:
    cmd: python src/models/evaluate_model.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
    - models/trained_model.pkl
    - src/models/evaluate_model.py
    outs:
    - data/predicted_data/predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false
